### ISSUE TITLE
cannot start jetforce after upgrade to v0.3.0

### ISSUE THREAD

**Issue by cremesk** [michael-lazar/jetforce#28]
hello,

i have update my jetforce server to the current release. after this step i cannot start the service. :/

```
May 31 08:46:14 core.envs.net systemd[1]: Started Jetforce Server - gemini protocol server.
May 31 08:46:14 core.envs.net jetforce[21206]: Traceback (most recent call last):
May 31 08:46:14 core.envs.net jetforce[21206]:   File "/usr/local/bin/jetforce", line 6, in <module>
May 31 08:46:14 core.envs.net jetforce[21206]:     from jetforce.__main__ import main
May 31 08:46:14 core.envs.net jetforce[21206]:   File "/usr/local/lib/python3.7/dist-packages/jetforce/__init__.py", line 8, in <module>
May 31 08:46:14 core.envs.net jetforce[21206]:     from .protocol import GeminiProtocol
May 31 08:46:14 core.envs.net jetforce[21206]:   File "/usr/local/lib/python3.7/dist-packages/jetforce/protocol.py", line 8, in <module>
May 31 08:46:14 core.envs.net jetforce[21206]:     from twisted.internet.address import IPv4Address, IPv6Address
May 31 08:46:14 core.envs.net jetforce[21206]:   File "/usr/local/lib/python3.7/dist-packages/twisted/internet/address.py", line 101, in <module>
May 31 08:46:14 core.envs.net jetforce[21206]:     @attr.s(hash=False, repr=False, eq=False)
May 31 08:46:14 core.envs.net jetforce[21206]: TypeError: attrs() got an unexpected keyword argument 'eq'
May 31 08:46:14 core.envs.net systemd[1]: jetforce.service: Main process exited, code=exited, status=1/FAILURE
May 31 08:46:14 core.envs.net systemd[1]: jetforce.service: Failed with result 'exit-code'.
```

**Comment by michael-lazar** [comment]
Hi,

Try updating your attrs dependency:

```
pip install attrs --upgrade
```

**Comment by cremesk** [comment]
great that helped. now everything works fine here! =)
